export type STATISTICS_TYPE = "CONTEXT_RETRIEVE" | "SOURCE_UPDATE" | "EMBEDDER_UPSERT" | "EMBEDDER_GENERATE" | "EMBEDDER_DELETE" | "WORKFLOW_RUN" | "CONTEXT_UPSERT" | "TOOL_CALL" | "AGENT_RUN";

export const STATISTICS_TYPE_ENUM = {
    CONTEXT_RETRIEVE: "CONTEXT_RETRIEVE",
    SOURCE_UPDATE: "SOURCE_UPDATE",
    EMBEDDER_UPSERT: "EMBEDDER_UPSERT",
    EMBEDDER_GENERATE: "EMBEDDER_GENERATE",
    EMBEDDER_DELETE: "EMBEDDER_DELETE",
    WORKFLOW_RUN: "WORKFLOW_RUN",
    CONTEXT_UPSERT: "CONTEXT_UPSERT",
    TOOL_CALL: "TOOL_CALL",
    AGENT_RUN: "AGENT_RUN"
};
